# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathitems', '0002_mathitem_defines'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem'),
        ),
    ]
