# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem')),
            ],
            options={
                'db_table': 'item_validations',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('isbn10', 'ISBN-10'), ('isbn13', 'ISBN-13')], max_length=8)),
                ('source_value', models.CharField(max_length=255)),
                ('metadata', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sources',
            },
        ),
        migrations.AddField(
            model_name='itemvalidation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validations.Source'),
        ),
    ]
