# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mathitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('isbn10', 'ISBN-10'), ('isbn13', 'ISBN-13')], max_length=8)),
                ('source_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='itemvalidation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='validations.Source'),
        ),
    ]
