# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
