# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('D', 'definition'), ('T', 'theorem'), ('P', 'proof')], max_length=1)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(choices=[('D', 'definition'), ('T', 'theorem'), ('P', 'proof')], max_length=1)),
                ('body', models.TextField(blank=True)),
            ],
        ),
    ]
