# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathitems', '0001_initial'),
        ('concepts', '0002_add_wildcard_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concepts.Concept')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem')),
            ],
            options={
                'db_table': 'concept_refs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='conceptreference',
            unique_together=set([('item', 'concept')]),
        ),
    ]
