# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_add_wildcard_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdependency',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemdep_item', to='mathitems.MathItem'),
        ),
    ]
