# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathitems', '0001_initial'),
        ('concepts', '0003_create_model_conceptreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepts', models.ManyToManyField(to='concepts.Concept')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mathitems.MathItem')),
                ('uses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mathitems.MathItem')),
            ],
            options={
                'db_table': 'item_deps',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemdependency',
            unique_together=set([('item', 'uses')]),
        ),
    ]
