# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_create_model_itemdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_count', models.IntegerField()),
                ('def_count', models.IntegerField()),
                ('concept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='concepts.Concept')),
            ],
            options={
                'db_table': 'concept_meta',
            },
        ),
    ]
