# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('perms', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
