# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


def set_defaults(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserData = apps.get_model('userdata', 'UserData')
    for user in User.objects.all():
        UserData.objects.new_user(user)


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_defaults)
    ]
