# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keywords', '0002_auto_20170402_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.Keyword')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Media')),
            ],
            options={
                'db_table': 'media_keyword',
            },
        ),
        migrations.AlterUniqueTogether(
            name='mediakeyword',
            unique_together=set([('media', 'keyword')]),
        ),
    ]
