# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_media_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SVGImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media')),
            ],
            options={
                'db_table': 'svgimage',
            },
        ),
    ]
