# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mathitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEquation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=32)),
                ('format', models.CharField(max_length=10)),
                ('math', models.TextField()),
                ('access_at', models.DateTimeField(auto_now_add=True)),
                ('html', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'cached_eqn',
            },
        ),
        migrations.CreateModel(
            name='Equation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('math', models.TextField()),
            ],
            options={
                'db_table': 'equations',
            },
        ),
        migrations.CreateModel(
            name='ItemEquation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'item_eqns',
            },
        ),
        migrations.CreateModel(
            name='RenderedEquation',
            fields=[
                ('eqn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equations.Equation')),
                ('hash', models.CharField(db_index=True, max_length=32)),
                ('html', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'rendered_eqn',
            },
        ),
        migrations.AddField(
            model_name='itemequation',
            name='equation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equations.Equation'),
        ),
        migrations.AddField(
            model_name='itemequation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem'),
        ),
        migrations.AlterUniqueTogether(
            name='itemequation',
            unique_together=set([('item', 'equation')]),
        ),
    ]
