# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathitems', '0001_initial'),
        ('equations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEquation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equations.Equation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem')),
            ],
            options={
                'db_table': 'item_eqns',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemequation',
            unique_together=set([('item', 'equation')]),
        ),
    ]
