# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0002_create_model_itemequation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equation',
            old_name='draft_access_at',
            new_name='cache_access',
        ),
        migrations.AddField(
            model_name='equation',
            name='error',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='equation',
            name='html',
            field=models.TextField(blank=True),
        ),
    ]
