# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0003_auto_20170402_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderedEquation',
            fields=[
                ('eqn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equations.Equation')),
                ('html', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'rendered_eqn',
            },
        ),
        migrations.RemoveField(
            model_name='equation',
            name='error',
        ),
        migrations.RemoveField(
            model_name='equation',
            name='html',
        ),
    ]
