# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0004_auto_20170407_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEquation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('math', models.TextField()),
                ('access_at', models.DateTimeField(auto_now_add=True)),
                ('html', models.TextField(blank=True)),
                ('error', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='equation',
            name='cache_access',
        ),
    ]
