# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0004_auto_20170407_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equation',
            name='math',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterUniqueTogether(
            name='equation',
            unique_together=set([('format', 'math')]),
        ),
    ]
