# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equations', '0005_auto_20170618_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedequation',
            name='hash',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renderedequation',
            name='hash',
            field=models.CharField(db_index=True, default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cachedequation',
            table='cached_eqn',
        ),
    ]
