# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathitems', '0003_mathitem_parent'),
        ('drafts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mathitems.MathItem'),
        ),
    ]
